[package]
name = "indicatif-multibar"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
indicatif = { version="0.17.8", features = ["tokio"] }
indicatif-log-bridge = "0.2.2"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["full"] }
